os: unstable

environment:
  GH_TOKEN:
      secure: Ga+40bO3lQTmQOxV/e8JwZyd0SukxC6SFRlDZ1B478dZ29qxXDsWzStTdDt0FXg3
  matrix:
    - nodejs_version: 7

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '0.0.1-dev.{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn
  - cd app && yarn

test_script:
  - node --version
  - yarn lint

build_script:
  - yarn package

artifacts:
  - path: release\win-unpacked
    name: moviecast-portable
  - path: release\*.exe
