version: 2
jobs:
  build:
    working_directory: ~/moviecast-desktop
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Package
          command: yarn package
      - store_artifacts:
          path: release
          prefix: release